language: python

python:

  - "3.6"

services:
  - postgresql

env:
  -DJANGO=3.0.7 DB=postgresql

install:
  - pip install -r requirements.txt

before_script:
  - cp .env.example .env
  - psql -c 'create database test_db;' -U postgres
  - python manage.py makemigrations accounts
  - python manage.py migrate

script:
  - python manage.py test